---
- name: Install useful pacman packages
  pacman:
    name: "{{ pacman_packages }}"
  become: true

- name: Install useful pip packages
  become: yes
  become_user: {{ user }}
  pip:
    name: "{{ pip_pacages }}"
    extra_args: --user

- name: Install useful aur packages
  aur:
    name: "{{ aur_packages }}"

- name: Create home folder structure
  file:
    path: "{{ home }}/{{ item }}"
    state: directory
  with_items:
    - "{{ projects_folder }}"
    - "{{ additional_folders }}"

- name: Vim stuff
  block:
    - name: Install vim
      pacman:
        name:
          - vim
        state: latest
      become: true
    - name: make sure vim has autoload dir
      file:
        path: "{{ home }}/.vim/autoload"
        state: directory
    - name: install vimplug for vim
      get_url:
        url: >
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ home }}/.vim/autoload/plug.vim"
          # TODO also install the plugins while we're at it

