---
- hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
    - name: Set home folder
      set_fact:
        home: "/home/{{ user.name }}"
  roles:
    - basics
    - lunarvim
    - misc
    - dotfiles
    - private_dotfiles

