---
- hosts: localhost
  tasks:
    - name: Install vim lol
      pacman:
        name:
          - nodejs
          - npm
          - yay
          - vim
          - fish  
          - xdotool
          - python2
          - python2-pip
          - python-pip
          - tmux
          - xclip
          # required for ergodox wally
          - webkit2gtk
          - kitty
          - ripgrep
      become: true
    - name: install neovim
      get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        dest: /usr/local/bin/nvim
        mode: '755'
      become: true
    - name: neovim autoload directory
      file:
        path: /home/cris/.local/share/nvim/site/autoload
        state: directory
    - name: install vimplug for neovim
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        # TODO username var
        dest: '/home/{{ user.name }}/.local/share/nvim/site/autoload/plug.vim'
    - name: pip packages
      pip:
        name:
          - virtualenv
    - name: neovim python2
      pip:
        name:
          - pynvim
          - neovim
        # TODO create a username var
        virtualenv: /home/cris/.pynvim
        virtualenv_python: python2
    - name: neovim python3
      pip:
        name:
          - pynvim
          - neovim
        # create a username var
        virtualenv: /home/cris/.pynvim3
    - name: I like fish to be in /usr/local/bin
      file:
        dest: /usr/local/bin/fish
        src: /usr/bin/fish
        state: link
      become: true
    - name: check if Monego fonts is installed
      shell: fc-list | grep Monego
      register: monego_installed
      ignore_errors: yes
    - name: create Monego font directory
      file:
        path: /home/cris/.fonts/m
        state: directory
      when: monego_installed.stdout == ""
    - name: Download Monego font
      get_url:
        url: https://github.com/cseelus/monego/raw/master/Monego-Nerd-Font/Monego%20Regular%20Nerd%20Font.otf
        dest: /home/cris/.fonts/m/Monego_Regular_Nerd_Font.otf
      when: monego_installed.stdout == ""
    - name: Install Monego font
      shell:
        cmd: fc-cache -f -v
      when: monego_installed.stdout == ""
    - name: Generate ssh key
      community.crypto.openssh_keypair:
        path: /home/cris/.ssh/id_rsa
    - name: install neovim for npm
      npm:
        name: neovim
        global: yes
      become: true

# TODO handle wallpaper. ATM it's in /home/cris/Downloads. Should be in something like /usr. Setting is in .config/plasmarc and .config/plasmashellrc
# TODO make sure the .vim dir exists
