- name: Clone the private dotfiles repo
  git:
    repo: "{{ private_dotfiles_url }}"
    dest: "{{ home }}/.local/utils"
    update: false
  register: private_dotfiles

- name: Deploy dotfiles
  shell: "{{ home }}/.local/utils/laptop/deploy.sh"
  when: private_dotfiles.changed
